//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary_Development_System_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempWord
    {
        public int Id { get; set; }
        public string Word { get; set; }
        public int Status { get; set; }
        public int InterestId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int AcceptanceVote { get; set; }
        public int RejectionVote { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public string Content { get; set; }
        public int UserId { get; set; }
    
        public virtual Interest Interest { get; set; }
    }
}
